### ISSUE TITLE
no lidarr-automated-downloader.bash

### ISSUE THREAD

**Issue by t3rminalx** [RandomNinjaAtk/docker-lidarr-lad#18]
Hey.

I've created the docker container tonight for the first time but there is no lidarr-automated-downloader.bash file or a scripts directory in the config directory.

Any help would be appreciated.

Thanks

**Comment by RandomNinjaAtk** [comment]
If you pulled down this docker image, everything is included. How did you pull down the image?

**Comment by t3rminalx** [comment]
I created a docker compose and pulled it from the docker hub.

https://hub.docker.com/r/randomninjaatk/lidarr-lad

**Comment by RandomNinjaAtk** [comment]
I'll need to setup a test instance, but the image has everything so, if it didn't work, it must be something else causing it...

**Comment by RandomNinjaAtk** [comment]
Tested using a new installation, and I cannot reproduce the problem. It must be something with your setup. Maybe try using a different machine/setup to try it on...
