### ISSUE TITLE
Lidarr API not pulled from config.xml correctly

### ISSUE THREAD

**Issue by lokiberra** [RandomNinjaAtk/docker-lidarr-lad#21]
21-lad-setup.bash has:
echo 'LidarrApiKey="$(grep "<ApiKey>" /config/config.xml | sed "s/\  <ApiKey>//;s/<\/ApiKey>//")"' >> "/scripts/lad-config"

LidarrAPIKey in lad-config becomes:
LidarrApiKey="$(grep "<ApiKey>" /config/config.xml | sed "s/\  <ApiKey>//;s/<\/ApiKey>//")"

which causes LAD not to communicate with Lidarr

**Comment by lokiberra** [comment]
Using this should fix the problem:

echo LidarrApiKey= "$(grep 'ApiKey' /config/config.xml | awk -F">" '{print $2}' | awk -F"<" '{print $1}')" >> "/scripts/lad-config"

**Comment by RandomNinjaAtk** [comment]
Interesting that your bringing this up, I've not had any issues with this in my own experience. Are you sure its not something else?

Also running my command straight from the CLI produces the key without issue.

**Comment by RandomNinjaAtk** [comment]
Your method using awk also works, but so does mine. Also the original command you referenced looks like this:

https://github.com/RandomNinjaAtk/docker-lidarr-lad/blob/9b956d52cadebf8be573461491fab5e6476f6c7a/root/etc/cont-init.d/21-lad-setup.bash#L100

Which is different then what you listed above. I know this script is working for others, so I don't think this is a bug. Maybe some other issue with your setup...

**Comment by lokiberra** [comment]
I saw this before I saw the issue with the url base, which actually was my connection issue. I restarted with the url base and it works fine though the config file does not actually have the api key but the bash code as I put in my first comment

**Comment by RandomNinjaAtk** [comment]
Glad it's working

**Comment by lokiberra** [comment]
Looks like it's been working good last night. Thanks for making it 👍
