### ISSUE TITLE
Josep Permission issues

### ISSUE THREAD

**Issue by neek0la** [RandomNinjaAtk/docker-lidarr-lad#23]
Seems that im downloading the songs to the temp download dir but lidarr cannot move the files to its own folder once downloaded. 
It then cleans the temp download folder and i assume deletes all the files.

Major Error i can see in log is
`chown: invalid user: 'josep:josep'`

How can i change the user?

**Comment by RandomNinjaAtk** [comment]
No you cannot, the default user is abc. Use the pgid and puid parameters.

https://github.com/RandomNinjaAtk/docker-lidarr-lad/blob/master/README.md#parameters

**Comment by neek0la** [comment]
I ssh with admin to my NAS and got this id
`admin@NAS:~$ id
uid=1024(admin) gid=100(users) groups=100(users),101(administrators)
`
Still no success
`User uid:    1024
User gid:    101`


One thing i noticed when starting the container that looks out of place is `HEAD is now at a6a99b6 Force permissions to josep:josep user`

Once the cron job starts this is and example of what im getting 

`Matching 10 tracks with Beets
unreadable file: /storage/downloads/lidarr/deezloaderremix/deezloaderremix/deezloaderrem
mv: cannot move '/storage/downloads/lidarr' to a subdirectory of itself, '/storage/downloads/lidarr/lidarr-import/LEN - It'\''s Easy If You Try (2013) (ALBUM) (WEB)-DREMIX/lidarr'
--
Setting folder permissions (777)
chown: invalid user: 'josep:josep'
Setting file permissions (666)
chown: invalid user: 'josep:josep'

Notified Lidarr to scan "/storage/downloads/lidarr/lidarr-import/LEN - It's Easy If You Try (2013) (ALBUM) (WEB)-DREMIX" for import
--
Cleaning Download directory...
`

**Comment by RandomNinjaAtk** [comment]
Are you sure your using the right container? And not someone eles's fork of this?

Because the fact that the chown user is josep:josep and not abc:bac, ie: see here:

https://github.com/RandomNinjaAtk/docker-lidarr-lad/blob/5bfca4a4d603757012f1fef19c96a90e632b80bd/root/etc/cont-init.d/21-lad-setup.bash#L125

Seems to me like your not running this container, but someone elses....

**Comment by neek0la** [comment]
You're right.
OMG what a silly mistake.

Keep up the great work
