### ISSUE TITLE
Assist in getting docker running

### ISSUE THREAD

**Issue by justinglock40** [RandomNinjaAtk/docker-lidarr-lad#26]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/23133649/79579412-8fd7fa00-8095-11ea-8dbe-f8f179929172.png">

<img width="291" alt="image" src="https://user-images.githubusercontent.com/23133649/79579530-b007b900-8095-11ea-9e0a-441bea188f73.png">

Can you explain exactly how the paths should be matched? The two images about are confusing me. Below is my current mapping?

<img width="506" alt="image" src="https://user-images.githubusercontent.com/23133649/79579631-d4639580-8095-11ea-9c27-1d2368e35cc0.png">

Can you advise on what should be done? Script logs just shows this.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/23133649/79579693-e9d8bf80-8095-11ea-9d38-e07a59cf0159.png">

**Comment by justinglock40** [comment]
So I got the paths matched up, but the script adds this folder but write up says map out ~/deezloaderremix

<img width="619" alt="image" src="https://user-images.githubusercontent.com/23133649/79581421-679dca80-8098-11ea-8d1a-af2ef5281d49.png">

**Comment by justinglock40** [comment]
Got everything fixed up.

**Comment by RandomNinjaAtk** [comment]
Just noticed this... glad you figured it out. Sometimes I forget to make documentation updates as I make changes....
