### ISSUE TITLE
ERROR: No fuzzy match found...

### ISSUE THREAD

**Issue by kiityman1** [RandomNinjaAtk/docker-lidarr-lad#27]
`Global Settings
Download Client: Download Directory: /storage/downloads/lidarr/dlclient
Lidarr Temp Import Location: /storage/downloads/lidarr/lidarr-import
Download Quality: FLAC
Download Bitrate: lossless
Download Track Count Verification: Enabled
Replaygain Tagging: Disabled
Beets Tagging: Enabled
Total Number of Albums To Process: 1
DL Client Concurrency: 1

Begin finding downloads...

Lidarr Artist Name: Lin‐Manuel Miranda (LID: 1 :: MBID: 925c7673-0e85-410f-b7e4-d9705a7aa619)
Lidarr Album Title: Hamilton: An American Musical (1 of 1)
Lidarr Album Year: 2015
Lidarr Album Type: album
Lidarr Album Track Count: 46
ERROR: Fallback to musicbrainz for url...
ERROR: "Lin‐Manuel Miranda"... musicbrainz id: 925c7673-0e85-410f-b7e4-d9705a7aa619 is missing deezer link, see: "/config/scripts/musicbrainzerror.log" for more det
ail...
Attemtping fuzzy search for Artist: Lin‐Manuel Miranda :: Album: Hamilton: An American Musical
ERROR: No fuzzy match found...`

Hi, I keep getting this error. I don't see the issue here and this album is on Deezer.

**Comment by RandomNinjaAtk** [comment]
If you read the log, and do what it says in "/config/scripts/musicbrainzerror.log" .... This will likely resolve itself. 

Please follow the included instructions. If it still doesn't work after that, please reopen or open a new issue

**Comment by kiityman1** [comment]
> If you read the log, and do what it says in "/config/scripts/musicbrainzerror.log" .... This will likely resolve itself.
> 
> Please follow the included instructions. If it still doesn't work after that, please reopen or open a new issue
> 
> Note, that making those changes can take up to a couple of hours, and you may need manually refresh lidarr artist data, to pull in the updates. You may also need to clear out the script log files...

Hi, I did what it said but now am getting this 

`root@1b37775991ba:/config/scripts# bash lidarr-automated-downloader.bash
Setting folder permissions (777)
Getting Lidarr missing and cutoff albums list for processing...
1 Missing Albums Found
0 Cutoff Albums Found

Global Settings
Download Client: 
Download Directory: /storage/downloads/lidarr/dlclient
Lidarr Temp Import Location: /storage/downloads/lidarr/lidarr-import
Download Quality: FLAC
Download Bitrate: lossless
Download Track Count Verification: Enabled
Replaygain Tagging: Disabled
root@1b37775991ba:/config/scripts# cat /config/scripts/notfound.log
Lin‐Manuel Miranda :: Hamilton: An American Musical (ID: 4c615b1c-5af9-432b-
9342-e39137ade143) :: Could not find a match using Release or Record Name, T
rack Count and Release Year
root@1b37775991ba:/config/scripts# `
