### ISSUE TITLE
Fuzzy Issue (2)

### ISSUE THREAD

**Issue by kiityman1** [RandomNinjaAtk/docker-lidarr-lad#29]
Hi, I did what it said but now am getting this. You said to open a new issue.

`root@1b37775991ba:/config/scripts# bash lidarr-automated-downloader.bash
Setting folder permissions (777)
Getting Lidarr missing and cutoff albums list for processing...
1 Missing Albums Found
0 Cutoff Albums Found

Global Settings
Download Client:
Download Directory: /storage/downloads/lidarr/dlclient
Lidarr Temp Import Location: /storage/downloads/lidarr/lidarr-import
Download Quality: FLAC
Download Bitrate: lossless
Download Track Count Verification: Enabled
Replaygain Tagging: Disabled
root@1b37775991ba:/config/scripts# cat /config/scripts/notfound.log
Lin‐Manuel Miranda :: Hamilton: An American Musical (ID: 4c615b1c-5af9-432b-
9342-e39137ade143) :: Could not find a match using Release or Record Name, T
rack Count and Release Year
root@1b37775991ba:/config/scripts# `

**Comment by RandomNinjaAtk** [comment]
So that album does not exist for that artist on the service, so it's working as expected...

**Comment by kiityman1** [comment]
> So that album does not exist for that artist on the service, so it's working as expected...
> 
> The matching isn't perfect, but in your case that album is non existent for the artist. So it cannot find something that does not exist.... If an album cannot be found with the same album artist, same album title and same track count, then it cannot be found.... Easiest way to check, is view the artist page and look to see if the album is available. This only works for album's, ep's and singles. Albums the artist is featured in will never be able to match.

But it exists here? https://musicbrainz.org/artist/925c7673-0e85-410f-b7e4-d9705a7aa619

**Comment by RandomNinjaAtk** [comment]
> 
> 
> > So that album does not exist for that artist on the service, so it's working as expected...
> > The matching isn't perfect, but in your case that album is non existent for the artist. So it cannot find something that does not exist.... If an album cannot be found with the same album artist, same album title and same track count, then it cannot be found.... Easiest way to check, is view the artist page and look to see if the album is available. This only works for album's, ep's and singles. Albums the artist is featured in will never be able to match.
> 
> But it exists here? https://musicbrainz.org/artist/925c7673-0e85-410f-b7e4-d9705a7aa619

It doesn't matter if it exists there, it doesn't exist on the service that is used to pull it. It cannot pull something that does not exist... its not magic....

**Comment by kiityman1** [comment]
> > > So that album does not exist for that artist on the service, so it's working as expected...
> > > The matching isn't perfect, but in your case that album is non existent for the artist. So it cannot find something that does not exist.... If an album cannot be found with the same album artist, same album title and same track count, then it cannot be found.... Easiest way to check, is view the artist page and look to see if the album is available. This only works for album's, ep's and singles. Albums the artist is featured in will never be able to match.
> > 
> > 
> > But it exists here? https://musicbrainz.org/artist/925c7673-0e85-410f-b7e4-d9705a7aa619
> 
> It doesn't matter if it exists there, it doesn't exist on the service that is used to acquire it. It cannot acquire something that does not exist...
> 
> Review the artist page on the service to see that it does not exist... (Only Albums, EPs, Singles can be matched, not featured albums)
> 
> Edit, on that note, I have updated some of the notfound logging to include a more descriptive error if you have updates enabled and reboot the container

The album is on Music Brainz and Deezer. I still do not see the issue. I pulled the latest but nothing changed in the notfound file.

Artist - https://musicbrainz.org/artist/925c7673-0e85-410f-b7e4-d9705a7aa619
Album - https://musicbrainz.org/release-group/4c615b1c-5af9-432b-9342-e39137ade143
Deezer- https://www.deezer.com/album/11244086

The script finds the correct musicbrainz id for the album and artist.

**Comment by RandomNinjaAtk** [comment]
The artist does not match, so it won't work. Album artists have to match. Deezers is listed as Various Artists, not the artist your referencing. Which is why it will never match. Add the album as a various artist album to lidarr and it will search for it. Album Name, Album Artist and Track counts must match on mbrainz and deezer in order to attempt to find a match. In your case, these are different. This is not a bug and everything is working as intended.
