### ISSUE TITLE
Some filenames are missing their artist

### ISSUE THREAD

**Issue by morlanth** [RandomNinjaAtk/docker-lidarr-lad#30]
In refererence to: https://github.com/RandomNinjaAtk/lidarr-automated-downloader/issues/10

The parameter for "albumTracknameTemplate" in deemix's config file (default.json) results in some albums' filenames to be void of an artist and as a result doesn't allow Lidarr to import.

Editing "/root/scripts/deemix/deemix/app/default.json" within the container and changing "albumTracknameTemplate": "%tracknumber% - %title%" to "albumTracknameTemplate": "%tracknumber% %artist% - %title%" fixes the issue. However, on restarting the container the modifications are reverted.

**Comment by RandomNinjaAtk** [comment]
?
