### ISSUE TITLE
beets with ftintitle

### ISSUE THREAD

**Issue by sindas** [RandomNinjaAtk/docker-lidarr-lad#32]
I was wondering if you'd consider including the ftintitle plugin for beets tagging so that tracks aren't stripped of the featuring tags in their track titles. This is super useful for hip-hop. Thank you for creating this wonderful package, it's fantastic.

**Comment by RandomNinjaAtk** [comment]
Have you tried adding it to the beets config file? Looks like it should just work if you did that...

**Comment by sindas** [comment]
I gave it a shot before I asked (sorry, I should have mentioned!), that is to say I added the featintitle plugin to the beets config, but I can't figure out how to actually make it work within Lidarr — it still tags everything the same as usual.

**Comment by RandomNinjaAtk** [comment]
Beets is seperate and works as part of the script. Depending on how you configure it, you may not see it. IE: If you have lidarr metadata tagging enabled, it will overwrite the beets data...

**Comment by sindas** [comment]
Looks like I had both turned on. So after I've turned off the Lidarr tagging, how can I force beets to go back over everything? I attempted to run 'beets ftintitle' from the console but beets isn't showing the plugin as available. 

<img width="303" alt="Screen Shot 2020-05-26 at 10 07 52 AM" src="https://user-images.githubusercontent.com/24991720/82917310-e3f9b800-9f38-11ea-8370-984bb7c58766.png">

**Comment by RandomNinjaAtk** [comment]
You need to specify the config file location, which is /config/scripts

**Comment by sindas** [comment]
Just to clarify, the command should be beet -c /config/scripts/beets-config.yaml ftintitle ?
I can't tell if it is doing anything.

<img width="303" alt="Screen Shot 2020-05-26 at 10 07 52 AM" src="https://user-images.githubusercontent.com/24991720/82920482-eeb64c00-9f3c-11ea-8ffd-01e542987d4d.png">

**Comment by RandomNinjaAtk** [comment]
You'd have to re-import the data into beets. The script actively wipes the beets db for every item that is downloaded to import. So there technically is no library associated with it in the files at the final location that lidarr is tracking. You'd have to perform a import of those files to be able to re-process them in beets.

I'd recommend you specify and use a different library file, that way script will not kill it with fire...

**Comment by sindas** [comment]
Thanks for all the help!! I got it to work finally.
