### ISSUE TITLE
RootFolderWatchingService | Error in Directory watcher

### ISSUE THREAD

**Issue by Mrpink200** [RandomNinjaAtk/docker-lidarr-lad#33]
Hi 
I m testing your latest release with default configuration on docker.
While scanning my library, (1500 albums), i face the following message :

RootFolderWatchingService | Error in Directory watcher for: {0}/mnt/musicbrainz-library/: The configured user limit (8192) on the number of inotify watches has been reached, or the operating system failed to allocate a required resource.
-- | --

Any idea ?

Many thxs

Alain

**Comment by RandomNinjaAtk** [comment]
Just making a guess, you likely didn't configure the docker correctly? Did you map the volumes? Set all the Parameters?

If lidarr is reporting that, it may just be a lidarr issue, and you'd need to report it there. But I don't think you mapped your volumes correctly to match the instructions.
