### ISSUE TITLE
Add New Musicbrainz ID doesn't work

### ISSUE THREAD

**Issue by pochacho99** [RandomNinjaAtk/docker-lidarr-lad#36]
Hi there, i can get your container to run fine, but when i try to add an artist using MBID (e.g. lidarr:ba0e7638-0cd6-4ff4-8987-c3e224d22c23) it says "Couldn't find any results for 'lidarr:ba0e7638-0cd6-4ff4-8987-c3e224d22c23'". I have a Lidarr container running on the same machine and it can find the artist just fine.

Also, am i understanding correctly that i don't need to setup Indexers or Download Clients in your container as it will search and download through the built-in Deemix?

**Comment by RandomNinjaAtk** [comment]
Lidarr is the same as the regular Linuxserver.io container. So the adding problem your experiencing is a Lidarr issue in general. If you want to compare against another container, use the linuxerserver lidarr container with the preview tag.

For your second question, that is correct. You don't technically need to setup any other clients/indexers if you don't want too

**Comment by pochacho99** [comment]
Thanks, i spun up a lidarr preview image and can't add via MBID, so i guess my problem is with the preview image. I have the exact same settings using a latest image and i can add with MBID just fine.

Anyway, using your container, i can add artists by name, Lidarr can correctly update info for albums and tracks, so my connection isn't the problem.

Can you shed some light on the attached logs? It appears to be matching up the artists to the correct Deezer ID, but is unable to match the albums and tracks? The notfound log says it can't find a match. Reading through the issues, i am aware that Musicbrainz and Deezer are not perfect matches, but the artists i have added all appear to exist in both Musicbrainz and Deezer.

[notfound.log](https://github.com/RandomNinjaAtk/docker-lidarr-lad/files/4861727/notfound.log)
[script-run.log](https://github.com/RandomNinjaAtk/docker-lidarr-lad/files/4861728/script-run.log)

**Comment by RandomNinjaAtk** [comment]
If you use archive mode, you can skip the script having to match, which can negate some of the issues with how it matches. But you can still require Lidarr to match it for import. 

Personally I mostly use archive mode, with forced imports. 

As for why it did not match, I’d have to replicate it to see if I can get more detail. 

You should report the Lidarr issue to Lidarr GitHub, since that seems to be an issue with Lidarr itself.

**Comment by pochacho99** [comment]
Archive mode certainly gets rid of the notfound.log, but i don't see any files being downloaded.

**Comment by RandomNinjaAtk** [comment]
If I had to guess, you didn’t configure all the docket options correctly.

**Comment by pochacho99** [comment]
Most likely, but I can't figure out what. The container doesn't throw up any errors and the logs don't say anything either. Guess I'll just have to do it manually and use Lidarr to import manually.

Regards,

Philip

________________________________

**Comment by RandomNinjaAtk** [comment]
Did you map your volumes correctly? From
The container cli, did you look in the download folder and import folder for data?

**Comment by pochacho99** [comment]
Yes of course, I can see both the dlclient and lidarr-import folders created in the volume I mapped, but both of them are empty. I don't see any errors being thrown up to indicate why

Regards,

Philip

________________________________

**Comment by RandomNinjaAtk** [comment]
If you modify this line:

https://github.com/RandomNinjaAtk/lidarr-automated-downloader/blob/a168e8afee8ddd00a23ce4026dd8fb58c7c22abd/lidarr-automated-downloader.bash#L1004

From:
‘’’
if cd "${PathToDLClient}" && $python -m deemix -b ${dlquality} "$albumurl" &> /dev/null && cd "${currentpwd}"; then
‘’’

To:
‘’’
if cd "${PathToDLClient}" && $python -m deemix -b ${dlquality} "$albumurl" && cd "${currentpwd}"; then
‘’’

You’ll be able to see the log output of the dL
Client.

**Comment by pochacho99** [comment]
Thanks for your support, I will give it a try
