### ISSUE TITLE
Add crontab time as an environment variable

### ISSUE THREAD

**Issue by ridizy** [RandomNinjaAtk/docker-lidarr-lad#40]
Thank you for your most excellent work!

Would it be possible to expose the crontab timing as a docker environment variable?

I have a largish library, and even after the initial musicbrainz cache creation, it takes close to 2 hours for the script to run.  I also don't add new wanted music very often.  It would be great to be able to configure the script to run less frequently.

As a side request, if `DLMODE` is set to `Audio`, perhaps the whole musicbrainz function could be skipped, as I understand it's not necessary for just audio? (I can add that this request to the script repo if you think it makes sense)

**Comment by RandomNinjaAtk** [comment]
Maybe migrate to using this instead: https://github.com/RandomNinjaAtk/docker-amd

I'm possibly going to be discontinuing this container in the near future because its easier to maintain as separate projects

**Comment by RandomNinjaAtk** [comment]
Please migrate to using the new docker
