### ISSUE TITLE
No downloads - possibly a downloader config problem?  

### ISSUE THREAD

**Issue by monkeyhat** [RandomNinjaAtk/docker-lidarr-lad#6]
Hey RandomNinja, 

After your great work (and help when I had issues) on the other downloader script, I was excited to see this all-in-one Docker image.  

The Lidarr part all seems to work just fine, but I'm encountering what is hopefully a small problem with the LAD part.  

In the script-run.log log file, I can see that the script matches albums, gets the album links and details, and reports that it's downloading the appropriate number of tracks ... but nothing ever appears in the download folder, and each album gives an error that the "Downloaded Track Count (0)" doesn't match the Album Track Count.  

I was thinking that I hadn't had to enter my login or cookie for the download site, as I would if I were manually using the downloader. Should I be doing that?  

Thanks in advance for any help, and keep up the amazing work!  

P.S.  I haven't mentioned the name of the download site, as I noticed you hadn't in your Readme.

**Comment by RandomNinjaAtk** [comment]
First would be, did you map the volumes correctly? 
/downloads - needs to be mapped as a volume, because it is required. See [parameters](https://github.com/RandomNinjaAtk/docker-lidarr-lad#parameters)

Second, the config file is not meant to be modified at all, in this container, if you modified it, you may have broken it because of that. All configuration options are to be handled by: [parameters](https://github.com/RandomNinjaAtk/docker-lidarr-lad#parameters)

If you reboot the container, or force an image update, it should fix the config file if you messed with it...

**Comment by RandomNinjaAtk** [comment]
If you update to the latest image, see if that fixes your issue. Make sure you mapped your /downloads path in the container if you haven't

**Comment by monkeyhat** [comment]
Thanks for the replies!  I should've realised not to edit the config file, given that it was resetting every time the container restarted!  

In the end, the problem on my side seems to have been the dlcheck setting.  I opened up the 1730 port on the container so I could look at the downloader queue and see what was happening, and noticed that it generally wasn't starting a download until the script had moved on an album or two. 
 
I'm running the container on a relatively low-powered NAS that also runs a bunch of other stuff, so I assume it's just taking a bit longer than usual.  I'm in no rush, so I've increased dlcheck to 60, and everything seems to be running just fine now.  

Thanks again for your great work!

**Comment by RandomNinjaAtk** [comment]
I was thinking that could also possibly be the issue. However, after thinking about the problem more, I think I can find a way to update LAD to no longer need that setting, which should make it a bit smarter.

**Comment by RandomNinjaAtk** [comment]
@monkeyhat A new update is out, should fix this issue, that setting is no longer needed. Let me know if its fixed after your updated to the latest...

**Comment by monkeyhat** [comment]
Hey @RandomNinjaAtk - everything seems to be working fine now.  Thanks again for your work!
